version: '2'
services:
  server:
    build:
      context: ..
      dockerfile: docker/server.docker
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    volumes:
      - ../:/go/src/app
    user: "${UID}:${GID}"
    entrypoint: docker/entry-dev.sh
  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_DB=riftforum_db
      - POSTGRES_USER=riftforum_user
      - POSTGRES_PASSWORD=riftforum_pass
    ports:
      - "8090:5432"
