version: '2'
services:
  server:
    container_name: riftforum_server_prod
    build:
      context: ..
      dockerfile: docker/server-prod.docker
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    entrypoint: docker/entry-prod.sh
  postgres:
    container_name: riftforum_postgres_prod
    image: postgres:9.6
    environment:
      - POSTGRES_DB=riftforum_db
      - POSTGRES_USER=riftforum_user
      - POSTGRES_PASSWORD=riftforum_pass
    volumes:
      - ./../postgres_data:/var/lib/postgresql/data
    ports:
      - "8090:5432"
  redis:
    container_name: riftforum_redis_prod
    image: redis:5-alpine
    volumes:
      - ./../redis_data:/data
    ports:
      - "8070:6379"
