version: '2'
services:
  server:
    build:
      context: ..
      dockerfile: docker/server.docker
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    volumes:
      - ../:/go/src/app
  postgres:
    build:
      context: ..
      dockerfile: docker/postgres.docker
    ports:
      - "8090:5432"
