version: '2'
services:
  server:
    container_name: riftforum-server
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
  postgres:
    container_name: riftforum-postgres
    image: postgres:9.6
    environment:
      - POSTGRES_DB=riftforum_db
      - POSTGRES_USER=riftforum_user
      - POSTGRES_PASSWORD=riftforum_pass
  redis:
    container_name: riftforum-redis
    image: redis:5-alpine
